### ISSUE TITLE
iOS compatibility

### ISSUE THREAD

**Issue by tao524** [esrever10/remnote-plugin-math-helper#1]
Thank you for developing such a great plugin.
I have been trying to find this plugin on the iOS app but in vain.
Is it incompatible with iOS?
Otherwise, could you give me instructions on how to use it on iOS?

**Comment by esrever10** [comment]
> Thank you for developing such a great plugin. I have been trying to find this plugin on the iOS app but in vain. Is it incompatible with iOS? Otherwise, could you give me instructions on how to use it on iOS?

I haven't tried the plugin on the mobile, so I haven't turned on mobile support, and I haven't had the energy to do it lately, sorry. Maybe I'll look into it later.

**Comment by tao524** [comment]
Thank you! It is a pity that this plugin is not currently available on iOS. I am eagerly looking forward to your mobile support.

**Comment by esrever10** [comment]
> Thank you! It is a pity that this plugin is not currently available on iOS. I am eagerly looking forward to your mobile support.

I have set up a development option called enableOnMobile that may meet your requirements, you need to give it a try.
