### ISSUE TITLE
The Latex input panel closed after a prompt selected

### ISSUE THREAD

**Issue by 00x0101101** [esrever10/remnote-plugin-math-helper#2]
Each time I select a prompt the plugin having given, input panel from the Latex block closed and my input was interrupted by this. And I have to reopen the Latex block.

**Comment by esrever10** [comment]
I see. I will try to fix it.

**Comment by esrever10** [comment]
> Each time I select a prompt the plugin having given, input panel from the Latex block closed and my input was interrupted by this. And I have to reopen the Latex block.

try the new version, I have fixed it
