### ISSUE TITLE
Inserting problem

### ISSUE THREAD

**Issue by hugomarins** [esrever10/remnote-plugin-math-helper#3]
The MathHelper does not insert content for me.

In the example below, I started writing "\fra", and the Helper showed me the list.
![image](https://github.com/esrever10/remnote-plugin-math-helper/assets/54500828/20b9748a-c6db-407f-91fe-07f326935d89)

But whether I try to use the Insert Selected Shortcut (enter; tried tab but nothing changed), or try to use the mouse, the helper simply closes, and does not insert the content of the function.
![image](https://github.com/esrever10/remnote-plugin-math-helper/assets/54500828/5bfee054-7820-4e87-aff4-fefb4d93dbcd)

![image](https://github.com/esrever10/remnote-plugin-math-helper/assets/54500828/5fad353a-2770-49d4-8737-aaa8dd9d2aef)

**Comment by esrever10** [comment]
> The MathHelper does not insert content for me.
> 
> In the example below, I started writing "\fra", and the Helper showed me the list. ![image](https://user-images.githubusercontent.com/54500828/250505921-20b9748a-c6db-407f-91fe-07f326935d89.png)
> 
> But whether I try to use the Insert Selected Shortcut (enter; tried tab but nothing changed), or try to use the mouse, the helper simply closes, and does not insert the content of the function. ![image](https://user-images.githubusercontent.com/54500828/250505992-5bfee054-7820-4e87-aff4-fefb4d93dbcd.png)
> 
> ![image](https://user-images.githubusercontent.com/54500828/250506165-5fad353a-2770-49d4-8737-aaa8dd9d2aef.png)

Please check the version. Is it 1.0.15?

**Comment by esrever10** [comment]
@hugomarins Please check the version. Is it 1.0.15? And what browser are you using?

**Comment by hugomarins** [comment]
Yes, it is up-to-date. I use Microsoft Edge, Chrome and the Desktop App for Windows. But I have never been able to insert the contents, this problem is not new for me.

**Comment by hugomarins** [comment]
By the way, your Plugin is terrific! Thanks for sharing!

**Comment by esrever10** [comment]
> Yes, it is up-to-date. I use Microsoft Edge, Chrome and the Desktop App for Windows. But I have never been able to insert the contents, this problem is not new for me. 

Oh, so wired. Please press F12 to check console log,maybe there's some useful information.You'd better show me a screenshot at your convenience.  You'd better send message to my discord directly.

**Comment by hugomarins** [comment]
I just uninstalled and installed again and it is now working perfectly!
Thanks for you attention and time!
