### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by dante7222** [esrever10/remnote-plugin-math-helper#4]
Power-up is working, but no pop-up and is autocomplete when i type latex

**Comment by esrever10** [comment]
I will check it

Georgii Sorokin ***@***.***> 于 2024年1月31日周三 上午3:24写道：

**Comment by esrever10** [comment]
> Power-up is working, but no pop-up and is autocomplete when i type latex

**Comment by esrever10** [comment]
Finally, I fixed the bug. Currently awaiting Remnotes review. New version: 1.0.16
