### ISSUE TITLE
there is no autocomplete suggestions in a popup menu.

### ISSUE THREAD

**Issue by albadore** [esrever10/remnote-plugin-math-helper#6]
- online and local, both i cannot find the autocomplete suggestions. 

- just like there's no mathhelper plugin.

- i tried unistall and download for many times, but failed. i don't konw what's wrong with it

- can you help me ?  i really want to use it.

**Comment by esrever10** [comment]
Remnote has been upgraded to so many versions that it is not compatible with my plugin. I haven't been able to update my plugin recently, and I thought that few people would use it. If you really want to use it, I'll try to fix it recently, may be this week or next week.

**Comment by esrever10** [comment]
> * online and local, both i cannot find the autocomplete suggestions.
> 
>     * just like there's no mathhelper plugin.
> 
>     * i tried unistall and download for many times, but failed. i don't konw what's wrong with it
> 
>     * can you help me ?  i really want to use it.

Remnote has been upgraded to so many versions that it is not compatible with my plugin. I haven't been able to update my plugin recently, and I thought that few people would use it. If you really want to use it, I'll try to fix it recently, may be this week or next week.

**Comment by esrever10** [comment]
Finally, I fixed the bug. Currently awaiting Remnotes review. New version: 1.0.16
